#include "aml.h"

#ifdef AML
#define STANDALONE
#endif
#ifdef PL
#define STANDALONE
#endif

#define MAX_SET_ELEMENTS 20

int do_set_element( node **np, ENVIRONMENT ce_env );

/**do_set
 *	parse a set.  This involves processing all the set elements,
 *	resulting in an array of note lists ("nla -- note list array").
 *	All the note lists in the array are merged into one list, which
 *	is returned.  do_set_element "uncircularizes" the returned
 *	note lists; but the result note_list ends up circular, as required.
 */
node *do_set( ENVIRONMENT set_env )

{
	node *nla[MAX_SET_ELEMENTS],*np,*note_list;
	int i,n = 0;
	float last_delay,out_delay,min_delay;
	int done = FALSE;
	int status = 0;
	enter("do_set");
	/*
	 * first build up the array of node lists
	 */
	while( (status = do_set_element(&np,set_env)) != 0 ) {
		if( status == COMPILE_ERR ) {
			for(i=0;i<n;i++) free_node_list( nla[i] );
			parse_error("Can't recognize item in a set");
			return NULL;
		}
		if( np != NULL ) {
			if( n > MAX_CHORD_ELEMENTS ) {
				for(i=0;i<n;i++) free_node_list( nla[i] );
				parse_error("Too many elements in a set");
				return NULL;
			}
			nla[n++] = np;
		}
	}
	if( nla[0] == NULL ) return NULL;
	/*
	 *	If the first element doesn't have any notes, then 
	 *	none of them will.  Given that there is at least
	 *	one note_on event, the first one in any list will
	 *	have delay 0.  So just arbitrarily put one in the
	 *	the note_list so we don't have to deal with the special
	 *	case of a NULL list at first.
	 */
	note_list = nla[0];		/* just use the very first one. */
	nla[0] = nla[0]->next;          /* fix up the array list. */
	note_list->next = note_list;	/* make the list circular */
	/*
	 *      Now go through the merge.  Brute force here.  Pass through
	 *	the array of lists, processing each list in turn.
	 *	Look at the top element.  If it has a 0 delay, move it to the
	 *	output list.  Repeat until a non-zero delay element is at the
	 *	top of the list.  Subtract the "last_delay"  from this element.
	 *	Again, move zero delay elements to the output list until there
	 *	is an element with a non-zero delay (or no element) at the
	 *	top of this list.  Keep passing over the array until all the
       	 *	lists are empty.
	 */
	last_delay = 0.0;
	out_delay = 0.0;
	done = FALSE;
	while( ! done ) {
		done = TRUE;
		min_delay = 1000000.0;
		for( i=0; i<n; i++ ) {
			if( nla[i] != NULL ) nla[i]->delay -= last_delay;
			while( (nla[i] != NULL) && (nla[i]->delay == 0) ){
				nla[i]->delay = out_delay;
				out_delay = 0.0;
				np = nla[i]->next;
				nla[i]->next = note_list->next;
				note_list->next = nla[i];
				note_list = nla[i];
				nla[i] = np;
			}
			if( nla[i] != NULL && nla[i]->delay < min_delay ) {
				min_delay = nla[i]->delay;/* can't be 0 now */
			}
			if( nla[i] != NULL ) done = FALSE; /* still something*/
		}
		last_delay = min_delay;
		out_delay = min_delay;
	}
	dmp_list(note_list);
	leave("do_set");
	return note_list;
}

/**do_set_element
 *	parse an individual set element.  The duration can't be
 *	changed by this routine, but the relative volume can.  If
 *	any notes were generated by this element, return the note list.
 *	in npp, otherwise npp is NULL.  Return FALSE when the '>' is
 *	reached, TRUE otherwise.
 */
int do_set_element( node **npp, ENVIRONMENT ce_env )

{
	char c;
	node *np = NULL;
	int result = TRUE;
	enter("do_set_element");
	*npp = NULL;
loop:
	c = nextc();
	if( isspace(c) ) goto loop;
	if( (c == ACCENT) || (c == SUBDUE) ) {
		ce_env.volume *= do_accent(c);
		goto loop;
	}
	if( c == END_SET ) {
		result = FALSE;
	} 
	else if( is_note_name(c) ) {
		np = do_note(c,&ce_env);
	}
	else if( c == BEGIN_SET ) {
		np = do_set(ce_env);
	}
	else if( c == BEGIN_SEQ ) {
		np = do_sequence(ce_env);
	}
	else if( c == BEGIN_PARAM ) {
		do_parameter(&ce_env);
	}
	else if( c == BEGIN_FUNC ) {
		do_function(&ce_env);
	}
	else {
#ifndef STANDALONE
		printf("<%c>\n",c);
#endif
		return COMPILE_ERR;
	}
	/* uncircularize the list, if any */
	if( np != NULL ) {
		*npp = np->next;
		np->next = NULL;
	}
	leave("do_set_element");
	return result;
}
