#include "aml.h"

node *do_set_element( int *status, ENVIRONMENT set_env );

/**do_set
 *	parse a set.  This involves processing all the set elements,
 *	resulting in an array of note lists ("nla -- note list array").
 *	All the note lists in the array are merged into one list, which
 *	is returned.  do_set_element "uncircularizes" the returned
 *	note lists; but the result note_list ends up circular, as required.
 */
node *do_set( ENVIRONMENT set_env )

{
	node *np;
	node *note_list = NULL;
	int i,n = 0;
	float last_delay,out_delay,min_delay;
	int done = FALSE;
	enter("do_set");
	/*
	 * first build up the array of node lists
	 */
	while( ! done ) {
		np = do_set_element(&done,set_env);
		if( done == ERROR ) {
			free_list( note_list );
			parse_error("Can't recognize item in a set");
			return NULL;
		}
		note_list = merge_lists(note_list,np);
	dmp_list(note_list);
	}
	leave("do_set");
	return note_list;
}

/**do_set_element
 *	parse an individual set element.  The duration can't be
 *	changed by this routine, but the relative volume can.  If
 *	any notes were generated by this element, return the note list.
 */
node* do_set_element( int *done, ENVIRONMENT ce_env )

{
	char c;
	node *np = NULL;

	enter("do_set_element");
	*done = FALSE;
loop:
	c = nextc();
	if( isspace(c) ) goto loop;
	if( (c == ACCENT) || (c == SUBDUE) ) {
		accent = do_accent(c);
		if( ce_env->volume * accent > 128 ) 
			ce_env->volume = 128;
		else
			ce_env->volume *= accent;
		goto loop;
	}
	if( c == END_SET ) {
		*done = TRUE;
	} 
	else if( is_note_name(c) ) {
		np = do_note(c,&ce_env);
	}
	else if( c == BEGIN_SET ) {
		np = do_set(ce_env);
	}
	else if( c == BEGIN_SEQ ) {
		np = do_seq(ce_env);
	}
	else if( c == BEGIN_PARAM ) {
/*		do_param(&ce_env);*/
	}
	else if( c == BEGIN_FUNC ) {
		do_fun(&ce_env);
	}
	else {
		*done = ERROR;
	}
	leave("do_set_element");
	return np;
}
