#include "aml.h"

#ifdef AML
#define STANDALONE
#endif
#ifdef PL
#define STANDALONE
#endif

#define MAX_SET_ELEMENTS 128

int do_set_element( node **np, ENVIRONMENT set_env );

/**do_set
 *	Parse a set.  This means recursively parse all the set elements.
 *	Each set element should yield a node list.  These node lists are
 *	kept in an array -- the nla ("node list array").
 *	All the node lists in the array are merged into one list, which
 *	is returned.
 */
node *do_set( ENVIRONMENT set_env )

{
	node *nla[MAX_SET_ELEMENTS];
	node *np;
	int i,n = 0;
	int status;
	enter("do_set");
	/*
	 * first build up the array of node lists
	 */
	nla[0] = nla[1] = NULL;
	while( (status = do_set_element(&np,set_env)) != NULL ) {
		if( status == COMPILE_ERR ) {
			for(i=0;i<n;i++) free_node_list( nla[i] );
			parse_error("Can't recognize item in a set");
			return NULL;
		}
		if( np != NULL ) {
			if( n > MAX_SET_ELEMENTS ) {
				for(i=0;i<n;i++) free_node_list( nla[i] );
				parse_error("Too many elements in a set");
				return NULL;
			}
			nla[n++] = np;
		}
	}
	/* now merge all the lists into one */
	for( i=1; i<n; i++) {
		np = merge_node_lists(nla[0],nla[i]);
		/* adjust the tail pointer */
		if( ((node *)nla[0]->xlink)->next == NULL ) np->xlink = nla[0]->xlink;
		else nla[0]->xlink = nla[i]->xlink;
		nla[0] = np;
	}

	dmp_list(nla[0]);
	leave("do_set");
	return nla[0];
}

/**do_set_element
 *	parse an individual set element.  The duration can't be
 *	changed by this routine, but the relative volume can.  If
 *	any notes were generated by this element, return the node list.
 *	in npp, otherwise npp is NULL.  Return FALSE when the END_SET is
 *	reached, TRUE otherwise.
 */
int do_set_element( node **npp, ENVIRONMENT set_env )

{
	char c;
	node *np = NULL;
	int result = TRUE;
	enter("do_set_element");
	*npp = NULL;
loop:
	c = nextc();
	if( isspace(c) ) goto loop;
	if( (c == ACCENT) || (c == SUBDUE) ) {
		set_env.volume *= do_accent(c);
		goto loop;
	}
	if( c == END_SET ) {
		result = FALSE;
	} 
	else if( is_note_name(c) ) {
		np = do_note(c,&set_env);
	}
	else if( c == BEGIN_SET ) {
		np = do_set(set_env);
	}
	else if( c == BEGIN_SEQ ) {
		np = do_sequence(set_env);
	}
	else if( c == BEGIN_PARAM ) {
		do_parameter(&set_env);
	}
	else if( c == BEGIN_FUNC ) {
		do_function(&set_env);
	}
	else {
#ifndef STANDALONE
		printf("<%c>\n",c);
#endif
		return COMPILE_ERR;
	}
	leave("do_set_element");
	return result;
}
