#include "aml.h"
node *do_set_element( int *status, ENVIRONMENT *env );

float accent;

/**do_set
 *	parse a set.  This involves processing all the set elements,
 *	resulting in an array of note lists ("nla -- note list array").
 *	All the note lists in the array are merged into one list, which
 *	is returned.  do_set_element "uncircularizes" the returned
 *	note lists; but the result note_list ends up circular, as required.
 */
node *set( char c, ENVIRONMENT *env )

{
	node *np;
	node *note_list = NULL;
	int done = FALSE;
	enter("set");

	if( c != BEGIN_SET ) {
		error("set: no beginning\n",NULL);
	}

	/*
	 * first build up the array of node lists
	 */
	while( ! done ) {
		np = do_set_element(&done,env);
		if( done == ERROR ) {
			free_list( note_list );
			parse_error("Can't recognize item in a set");
			return NULL;
		}
		note_list = merge_lists(note_list,np);
	dmp_list(note_list);
	}
	leave("set");
	return note_list;
}

/**do_set_element
 *	parse an individual set element.  The duration can't be
 *	changed by this routine, but the relative volume can.  If
 *	any notes were generated by this element, return the note list.
 */
node* do_set_element( int *done, ENVIRONMENT *env )

{
	char c;
	node *np = NULL;

	enter("do_set_element");
	*done = FALSE;
loop:
	c = nextc();
	if( isspace(c) ) goto loop;
	if( isdigit(c) ) {
		parse_error("set: can't modify duration\n");
		*done = ERROR;
		return NULL;
	}
	if( c == END_SET ) {
		*done = TRUE;
		return np;
	} 
	np = basic(c,env);
	leave("do_set_element");
	return np;
}
